version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 698355729228.dkr.ecr.us-east-2.amazonaws.com
      - echo Building the Docker image...
      - docker build -t eks-lab-5 .
  build:
    commands:
      - echo Pushing the Docker image...
      - docker tag eks-lab-5 698355729228.dkr.ecr.us-east-2.amazonaws.com/eks-lab-5:latest
      - docker push 698355729228.dkr.ecr.us-east-2.amazonaws.com/eks-lab-5
      - echo Updating the image in the Kubernetes deployment...
      - sed -i.bak 's|698355729228.dkr.ecr.us-east-2.amazonaws.com/eks-lab-5|698355729228.dkr.ecr.us-east-2.amazonaws.com/eks-lab-5|g' deployment.yaml
  post_build:
    commands:
      - echo Applying Kubernetes manifests...
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

artifacts:
  files: 
    - deployment.yaml
    - service.yaml
