version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo Installing kubectl...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin
      - kubectl version --short --client
      - echo Installing AWS IAM Authenticator...
      - curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mv ./aws-iam-authenticator /usr/local/bin
      - echo Installing eksctl...
      - curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/v0.68.0/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      - mv /tmp/eksctl /usr/local/bin

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 587027614473.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ecr .
      - docker tag ecr:latest 587027614473.dkr.ecr.us-east-1.amazonaws.com/ecr:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 587027614473.dkr.ecr.us-east-1.amazonaws.com/ecr:latest
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region us-east-1 --name eks
      - echo Deploying to Kubernetes cluster...
    - kubectl apply -f k8s-deployment.yml || echo "kubectl command failed"

artifacts:
  files: k8s-deployment.yml

